
const siteThemes = {
    name: 'fusion theme',
    colors: {
        darkBlueGray: '#283238',
        lightNavy: '#14449e',
        seaBlue: '#3a8efc',
        lightBlue: '#5ea5ec',
        blueBorder: '#84b2d7',
        highlightBlue: '#bedfff',
        blueHighlight: '#c2e1ff',
        lightBlueBorder: '#d9e9f6',
        blueGrayHover: '#e4eaf0',
        backgroundLight: '#f7fafc',
        backgroundLightBlue: '#f3f7fa',
        backgroundLightPurple: '#ece5f0',
        backgroundLightGray: '#f8f8f8',
        backgroundMidGray: '#f2f7fa',
        backgroundGray: '#edf2f5',
        disabledGray: '#c4c5cc',
        lightGray: '#a0a1ab',
        softGray: '#888',
        midGray: '#4c4c4c',
        darkGray: '#27303c',
        sunflowerYellow: '#ffdc00',
        darkerYellow: '#f7d128',
        midnightPurple: '#23013d',
        veryLightGray: '#f2f3f3',
        black: '#000000',
        white: '#ffffff',
        fadedGray: '#e4e7e9',
        graier: '#d5dee3',
        idle: '#FF9933',
        operating: '#4db6ac',
        off: '#630a6b',
        darkPink: '#c61a51',
        negativeTrend: '#ff7a6e',
        strongRed: '#990000',
        extraDarkGray: '#0b0c0c',
        tableHeader: '#e3eff9',
        redMapIndicator: '#e2445c',
        yellowMapIndicator: '#fdab3c',
        greenMapIndicator: '#00c875',
        grayMapIndicator: '#97a1a1',
        silhouetteGrey: '#F0F3F5',
        chartsPink: '#D33350',
        violet: '#8A2BE2',
        turquise: '#87F6F0',
        mustard: '#FECA00',
        flamingo: '#F19CBB',
        pink: '#FF4DA3',
        apple: '#A8E4A0',
        lavender: '#CCCCFF',
        cyan: '#2E5090',
        lightCornflowerBlue: '#C2E2FF',
        salmon: '#FFA07A',
        straw: '#E4D96F',
    },
    fontFamilies: {
        condensed: 'open sans condensed'
    }
};

export default siteThemes;
